Refactor notify action

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -4,7 +4,7 @@ author: Tien Mai (matidev@outlook.com)
 
 inputs:
   notifyUrl:
-    description: "Notify URL"
+    description: "Notify URL Endpoint"
     required: false
   notifyKey:
     description: "Notify API Key"
@@ -16,15 +16,24 @@ inputs:
 runs:
   using: "composite"
   steps:
-    - shell: bash
+    - name: "Send Notification"
+      shell: bash
+      env:
+        NOTIFY_URL: ${{ inputs.notifyUrl }}
+        NOTIFY_KEY: ${{ inputs.notifyKey }}
+        TARGET_BRANCH: ${{ inputs.targetBranch }}
       run: |
-        if [ -n "${{ inputs.notifyUrl }}" ] && [ -n "${{ inputs.notifyKey }}" ]; then
-          TARGET_BRANCH="${{ inputs.targetBranch }}"
-          if [ -z "$TARGET_BRANCH" ]; then
-            TARGET_BRANCH="${{ github.ref_name }}"
-          fi
-
-          curl -X POST -H "Content-Type: application/json" -H "X-Notify-Key: ${{ inputs.notifyKey }}" \
-               -d "{\"actor\":\"${{ github.actor }}\",\"event_name\":\"${{ github.event_name }}\",\"job\":\"${{ github.job }}\",\"ref_name\":\"$TARGET_BRANCH\",\"ref_type\":\"${{ github.ref_type }}\",\"repository\":\"${{ github.repository }}\",\"run_number\":\"${{ github.run_number }}\",\"triggering_actor\":\"${{ github.triggering_actor }}\",\"workflow\":\"${{ github.workflow }}\"}" \
-               ${{ inputs.notifyUrl }} || true
+        if [[ -z "$NOTIFY_URL" || -z "$NOTIFY_KEY" ]]; then
+          exit 0
         fi
+
+        if ! [[ "$NOTIFY_URL" =~ ^https?:// ]]; then
+          echo "Error: notifyUrl must be a valid HTTP/HTTPS URL."
+          exit 1
+        fi
+
+        TARGET_BRANCH="${TARGET_BRANCH:-${{ github.ref_name }}}"
+
+        curl -X POST -H "Content-Type: application/json" -H "X-Notify-Key: $NOTIFY_KEY" \
+               -d "{\"actor\":\"${{ github.actor }}\",\"event_name\":\"${{ github.event_name }}\",\"job\":\"${{ github.job }}\",\"ref_name\":\"$TARGET_BRANCH\",\"ref_type\":\"${{ github.ref_type }}\",\"repository\":\"${{ github.repository }}\",\"run_number\":\"${{ github.run_number }}\",\"triggering_actor\":\"${{ github.triggering_actor }}\",\"workflow\":\"${{ github.workflow }}\"}" \
+               "$NOTIFY_URL" || true
